"""
gravity_all.py — Task 1a gravity for one TTM + LaTeX/CSV table builder for the
cross-TTM comparison. Reuses the existing `gravity.run_gravity` and
`dataio.aggregate_ttm_to_bezirke`.

Workflow:
  1. For each TTM in the catalog:
       g = run_gravity_for_ttm(spec, tt_aligned, d06, bez)
     The orchestrator (step 4) provides `tt_aligned` once it has it in memory.

  2. After all TTMs processed:
       build_gravity_table(rows, tex_path, csv_path, *,
                           include_arsw_benchmark=True, bez=bez)
     emits a multi-row table in the style of ARSW Table III.
"""
from __future__ import annotations
from pathlib import Path
from typing import Iterable

import numpy as np
import pandas as pd

import dataio
import gravity

from .ttm_catalog import TTMSpec


# ---------------------------------------------------------------------------
# One-TTM gravity
# ---------------------------------------------------------------------------
def run_gravity_for_ttm(spec: TTMSpec, tt_aligned: np.ndarray, d06: dict,
                        bez: dict, *,
                        weight_mode: str = "emp",
                        n_bezirke: int = 12) -> dict:
    """Aggregate `tt_aligned` to Bezirke and run gravity (OLS + PPML).

    Parameters
    ----------
    spec : TTMSpec
        Metadata only (used for the label).
    tt_aligned : (N, N) ndarray
        Canonical-order block TTM (NaN-free, diagonal zero).
    d06 : dict
        `dataio.load_block_data(2006)` output (uses `obsvar` and `bzk_mod`).
    bez : dict
        `dataio.load_bezirke_matrices()` output: keys `prob`, `minutes`, `counts`.
    weight_mode : "emp" (employment-weighted), "simple" (uniform), or "both".
        "emp" matches ARSW Table III's preferred specification.
    n_bezirke : 12 by default (mod_bezirk groups).

    Returns
    -------
    dict with keys "label", "spec", "weight_mode", and one of "ols"/"ppml"/"ppml_counts"
    each being a `(eps_kappa, se, extra)` tuple (extras carry 'r2', 'n').
    """
    bzk_mod = d06["bzk_mod"]
    if weight_mode == "emp":
        w = d06["obsvar"][:, 1] + d06["obsvar"][:, 2]      # workplace + residence
    elif weight_mode == "simple":
        w = None
    else:
        raise ValueError(f"weight_mode must be 'emp' or 'simple', got {weight_mode!r}")
    tau = dataio.aggregate_ttm_to_bezirke(tt_aligned, bzk_mod,
                                          weight=w, n_bezirke=n_bezirke)
    g = gravity.run_gravity(bez["prob"], tau, bez["counts"])
    return {
        "label": spec.latex_name,
        "spec": spec,
        "weight_mode": weight_mode,
        "ols": g["ols"],
        "ppml": g["ppml"],
        "ppml_counts": g.get("ppml_counts", (np.nan, np.nan, {"n": 0})),
    }


# ---------------------------------------------------------------------------
# LaTeX + CSV table builders
# ---------------------------------------------------------------------------
def build_gravity_table(rows: Iterable[dict], tex_path: Path,
                        csv_path: Path | None = None, *,
                        include_arsw_benchmark: bool = True,
                        bez: dict | None = None,
                        caption: str | None = None,
                        label: str = "tab:gravity_cross_ttm") -> dict:
    """Write a booktabs LaTeX table and (optionally) a parallel CSV.

    The LaTeX table follows the style of ARSW Table III: each row is a TTM
    specification, with paired OLS / PPML / PPML(counts) columns reporting
    $\\hat\\varepsilon\\kappa$ and SE, plus the OLS $R^2$.
    """
    rows = list(rows)
    benchmark_row = None
    if include_arsw_benchmark and bez is not None:
        gb = gravity.run_gravity(bez["prob"], bez["minutes"], bez["counts"])
        benchmark_row = {
            "label": r"ARSW bilateral minutes (benchmark)",
            "ols": gb["ols"], "ppml": gb["ppml"],
            "ppml_counts": gb.get("ppml_counts", (np.nan, np.nan, {"n": 0})),
            "weight_mode": "n/a",
        }

    def _row_tex(r, *, italic_label: bool = False):
        ek_o, se_o, ex_o = r["ols"]
        ek_p, se_p, ex_p = r["ppml"]
        ek_c, se_c, ex_c = r["ppml_counts"]
        r2 = ex_o.get("r2", float("nan"))
        n = ex_o.get("n", float("nan"))
        lab = r["label"]
        if italic_label:
            lab = rf"\emph{{{lab}}}"
        return (
            f"{lab} & "
            f"{ek_o:.4f} & ({se_o:.4f}) & "
            f"{ek_p:.4f} & ({se_p:.4f}) & "
            f"{ek_c:.4f} & ({se_c:.4f}) & "
            f"{r2:.3f} & {int(n) if np.isfinite(n) else '--'} \\\\"
        )

    lines = []
    lines.append(r"% Auto-generated by orchestrator/gravity_all.py")
    lines.append(r"\begin{table}[h]")
    lines.append(r"\centering")
    if caption:
        lines.append(rf"\caption{{{caption}}}")
    lines.append(rf"\label{{{label}}}")
    lines.append(r"\begin{tabular}{lcccccccc}")
    lines.append(r"\toprule")
    lines.append(r" & \multicolumn{2}{c}{OLS} "
                 r"& \multicolumn{2}{c}{PPML ($\pi$)} "
                 r"& \multicolumn{2}{c}{PPML (counts)} & & \\")
    lines.append(r"\cmidrule(lr){2-3} \cmidrule(lr){4-5} \cmidrule(lr){6-7}")
    lines.append(r"Travel-time matrix "
                 r"& $\hat\varepsilon\kappa$ & SE "
                 r"& $\hat\varepsilon\kappa$ & SE "
                 r"& $\hat\varepsilon\kappa$ & SE "
                 r"& $R^2$ & $N$ \\")
    lines.append(r"\midrule")
    for r in rows:
        lines.append(_row_tex(r))
    if benchmark_row is not None:
        lines.append(r"\midrule")
        lines.append(_row_tex(benchmark_row, italic_label=True))
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    lines.append(r"\end{table}")
    tex_path = Path(tex_path)
    tex_path.parent.mkdir(parents=True, exist_ok=True)
    tex_path.write_text("\n".join(lines))

    if csv_path is not None:
        df_rows = []
        all_rows = rows + ([benchmark_row] if benchmark_row else [])
        for r in all_rows:
            ek_o, se_o, ex_o = r["ols"]
            ek_p, se_p, _    = r["ppml"]
            ek_c, se_c, _    = r["ppml_counts"]
            df_rows.append({
                "label": r["label"],
                "weight_mode": r.get("weight_mode", "n/a"),
                "ols_eps_kappa": ek_o, "ols_se": se_o, "ols_r2": ex_o.get("r2"),
                "ols_n": ex_o.get("n"),
                "ppml_eps_kappa": ek_p, "ppml_se": se_p,
                "ppml_counts_eps_kappa": ek_c, "ppml_counts_se": se_c,
            })
        csv_path = Path(csv_path)
        csv_path.parent.mkdir(parents=True, exist_ok=True)
        pd.DataFrame(df_rows).to_csv(csv_path, index=False)

    return {
        "tex_path": str(tex_path),
        "csv_path": str(csv_path) if csv_path is not None else None,
        "n_rows": len(rows) + (1 if benchmark_row else 0),
    }
